server:
  port: 8081

spring:
  application:
    name: user
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/usm?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: usm_admin
    password: 123456